spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bd_products
      username: admin
      password: 123456789

bank-example:
  business:
    rules:
      saving-accounts:
        max: 1
        maintenceFee: 0.00
      current-account:
        max: 1
        maintenceFee: 50.00
      fixed-term-deposit:
        max: 1
        interest-rate: 2.50